# Gmail configuration
GMAIL_TOKEN = '{"client_id":"762116245919-ueqmt3hq86mb7lquq0mmp10r532lnkb0.apps.googleusercontent.com","client_secret":"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","refresh_token":"1//04xeXzXyWDa2ZCgYIARAAGAQSNwF-L9IrHI9T1lkU0PXY3MO-Xk7vMt_9DwZym23SmYoGSnBIDk7IpkgOGIR8uArHyrqYq2XEpgo","token_uri":"https://oauth2.googleapis.com/token"}'
DEFAULT_RECIPIENT = "jhnapo2213@gmail.com"

# MotherDuck configuration
MOTHERDUCK_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiamhuYXBvMjIxM0BnbWFpbC5jb20iLCJlbWFpbCI6ImpobmFwbzIyMTNAZ21haWwuY29tIiwidXNlcklkIjoiZDYxODc4YjQtNzNhMi00ZmE5LWI3ZjQtMGRhNzg4NjJhNWFiIiwiaWF0IjoxNzA4MzgzNjE0LCJleHAiOjE3NDAwMDYwMDB9.KcYmWvJUJj7kJ0TPt_V3ulh_kMGcm2TIQcSpPXe_8JY"
