[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
enableXsrfProtection = true
fileWatcherType = "none"  # Disable file watching in cloud environments

[browser]
gatherUsageStats = false

[logger]
level = "info"
