[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
enableXsrfProtection = true
# Ensure we always use the correct entry point
entrypoint = "app/cloud_main.py"

[browser]
gatherUsageStats = false

[logger]
level = "info"
